# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore 
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output safe-sign-api/Safe-Sign.WebAPI.csproj
artifacts:
  files:
    - 'safe-sign-api/build_output/**/*'
  discard-paths: no

